[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "pzzldbot helps users by quickly summarizing content leveraging intelligent systems and diverse data-sources"
edition = "2021"
homepage = "https://github.com/FL03/tldr/wiki"
keywords = []
license = "Apache-2.0"
name = "pzzld-bot"
repository = "https://github.com/FL03/tldr"
version = "0.1.0"

[features]

test_env = []

[[bin]]
bench = false
name = "tldr"
path = "src/main.rs"
test = true

[build-dependencies]

[dev-dependencies]

[dependencies]
# Custom libraries
acme = { features = [], git = "https://github.com/FL03/acme", branch = "v0.2.4", version = "0.2.4" }
scsys = { features = [], version = "0.1.38" }

# API
axum = { features = ["headers", "http2", "macros"], version = "0.6.1" }
http = "0.2.8"
hyper = { features = ["full"], version = "0.14.23" }
tokio = { features = ["full"], version = "1.23.0" }
tower = "0.4.13"
tower-http = { features = ["full"], version = "0.3.5" }


# CLI
clap = { features = ["cargo", "derive", "env"], version = "4.0.32" }

# Logging
tracing = "0.1.37"
tracing-subscriber = { features = ["env-filter"], version = "0.3.16" }

# Misc
futures = "0.3.25"
serde = { features = ["derive"], version = "1" }
serde_json = "1"
strum = { features = ["derive"], version = "0.24.1" }

# Services
async-openai = "0.2.0"
teloxide = { features = ["macros"], version = "0.11.3" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
